config/routes.rb
Rails.application.routes.draw do
  scope(:path_names => { :new => "nueva", :edit => "editar" }) do
    resources :schedules, :path => 'citas'
  end
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#login'

  get '/administrar/:id' => 'departments#show'
  get '/administrar/:id/:date' => 'departments#show'
  post '/administrar/guardar' => 'schedules#save'

  get '/administrar-empleados' => 'schedules#employees' 
  get '/administrar-estudiantes' => 'schedules#students' 
  post '/toggle-course' => 'schedules#toggle_course'
  post '/toggle-unlimited' => 'schedules#toggle_unlimited'
  post '/toggle-vulnerable' => 'schedules#toggle_vulnerable'
  post '/generar-entrada' => 'schedules#generate_unlimited'

  get '/mis-entradas' => 'schedules#my_schedules'
  post '/guardar-verificacion' => 'schedules#save_checklist'

  get '/registro' => 'schedules#register'
  get '/registro/login' => 'schedules#register_login'
  post '/registro/iniciar-sesion' => 'schedules#register_do_login'
  get '/registro/logout' => 'schedules#register_logout'
  get '/registro/ver/:date' => 'schedules#register'
  get '/registro/entradas' => 'schedules#register_in'
  get '/registro/salidas' => 'schedules#register_out'
  get '/registro/entrada/:id' => 'schedules#check_in'
  post '/registro/guardar-entrada' => 'schedules#save_in'
  get '/registro/salida/:id' => 'schedules#check_out'
  post '/registro/guardar-salida' => 'schedules#save_out'

  get '/ocupacion' => 'schedules#occupation'

  get '/mis-estudiantes' => 'supervisors#my_students'
  post '/agregar-supervisor' => 'supervisors#add_supervisor'
  post '/borrar-supervisor' => 'supervisors#delete_supervisor'

  get '/reporte' => 'reports#index'
  post '/reporte' => 'reports#index'
  get '/reporte/xls' => 'reports#xls'
  post '/reporte/xls' => 'reports#xls'

  # get '/entrada/editar/:id' => 'schedules#edit'
  post '/cita/actualizar' => 'schedules#save_edit'


  post '/horas' => 'schedules#hours'

  
  root :to => 'schedules#index'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  	@date_start = params[:date_start]
  	@date_end = params[:date_end]
  	@department_id = params[:department_id]
    @rh_group = params[:rh_group]
  	@user_id = params[:user_id]

    if params[:show_type].blank? == 'E' 
      params[:show_type] = 'E'
    end

    @show_students = false


    if params[:show_type] == 'A' 
      @show_students = true
    end

    
    if @date_start.blank?
      @date_start = Time.now.strftime("%Y-%m-%d")
    end

    if @date_end.blank?
      @date_end = Time.now.strftime("%Y-%m-%d")
    end

  	@schedules = Schedule.joins(:user).where(work_date: @date_start..@date_end).order(:work_date, :in)

  	if !@department_id.blank?
  	  @schedules = @schedules.where('users.department_id': @department_id)
  	end

  	if !@user_id.blank?
  	  @schedules = @schedules.where('users.id': @user_id)
  	end

    if params[:show_type] == 'E' 
      @schedules = @schedules.where('users.is_student': false).where("users.rh_level <> 'CAT'")
    end

    if params[:show_type] == 'C' 
      @schedules = @schedules.where('users.rh_level': 'CAT')
    end

    if params[:show_type] == 'A' 
      @schedules = @schedules.where('users.is_student': true)
    end

    if !@rh_group.blank?
      @schedules = @schedules.where('users.rh_group': @rh_group)
    end

  end

  def xls
    @date_start = params[:date_start]
    @date_end = params[:date_end]
    @department_id = params[:department_id]
    @rh_group = params[:rh_group]
    @user_id = params[:user_id]

    if params[:show_students].to_i == 1
      @show_students = true
    else
      @show_students = false
    end
    
    if @date_start.blank?
      @date_start = Time.now.strftime("%Y-%m-%d")
    end

    if @date_end.blank?
      @date_end = Time.now.strftime("%Y-%m-%d")
    end

    @schedules = Schedule.joins(:user).where(work_date: @date_start..@date_end).order(:work_date, :in)

    if !@department_id.blank?
      @schedules = @schedules.where('users.department_id': @department_id)
    end

    if !@user_id.blank?
      @schedules = @schedules.where('users.id': @user_id)
    end

    if !@rh_group.blank?
      @schedules = @schedules.where('users.rh_group': @rh_group)
    end

    p = Axlsx::Package.new
    wb = p.workbook

    wb.add_worksheet(name: 'Asistencia') do |sheet|
      sheet.add_row ['ID', 'Nombre', 'Grupo', 'Nivel', 'Departamento', 'Fecha', 'Motivo', 'Autorizó', 'Entrada', 'Salida', 'Horas']
      @schedules.each do |s|
        id = s.user.rh_id rescue '--'
        nombre = s.user.fullname rescue '--'
        grupo = s.user.rh_group rescue '--'
        nivel = s.user.rh_level rescue '--'
        departamento = s.user.department.name rescue '--'
        fecha = s.work_date rescue '--'
        motivo = s.notes rescue '--'

        autorizo = s.authorized_by.fullname rescue '--'
        if s.user.location.name != 'Chihuahua'
          plus_in = s.in + 1.hours rescue '--'
          plus_out = s.out + 1.hours rescue '--'
          entrada = plus_in.strftime("%H:%M") rescue '--'
          salida = plus_out.strftime("%H:%M") rescue '--' 
        else 
          entrada = s.in.strftime("%H:%M") rescue '--'
          salida = s.out.strftime("%H:%M") rescue '--' 
        end

        horas = ((s.out - s.in) / 1.hours).round(2) rescue '--'

        
        sheet.add_row [id, nombre, grupo, nivel, departamento, fecha, motivo, autorizo, entrada, salida, horas]
      end 
    end
  
    p.serialize 'reporte.xlsx'
    render :file => 'reporte.xlsx'

  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<h1 class="department-name">Reporte</h1>
<form action="/reporte" method="post" id="reportform" name="reportform">
<table class="table is-fullwidth" style="font-size: 80% !important;">
  <tr>
    <th style="font-size: 80% !important;">Tipo</th>
  	<th style="font-size: 80% !important;">Departamento</th>
    <th style="font-size: 80% !important;">Grupo</th>
  	<th style="font-size: 80% !important;">Persona</th>
  	<th style="font-size: 80% !important;">Inicio</th>
  	<th style="font-size: 80% !important;">Fin</th>
  </tr>
  <tr>
    <td>
      <div class="select">
      <select style="font-size: 80% !important;" name="show_type" onchange="this.form.submit()">
        <%
        sel_E = ''
        sel_C = ''
        sel_A = ''
        sel_E = 'selected = "selected"' if params[:show_type] == 'E'
        sel_C = 'selected = "selected"' if params[:show_type] == 'C'
        sel_A = 'selected = "selected"' if params[:show_type] == 'A'
        %>
        <option value="E" <%= sel_E %>>Empleados</option>
        <option value="C" <%= sel_C %>>Catedras</option>
        <option value="A" <%= sel_A %>>Estudiantes</option>
      </select></div>
    </td>
    
  	<td>
  		<div class="select"><select style="font-size: 80% !important;" name="department_id" onchange="this.form.submit()">
  		  <option value="">--</option>
  		<% Department.order(:name).each do |d| 
  		  selected = ""
  		  selected = "selected = 'selected'" if d.id.to_i == @department_id.to_i %>

          <option value="<%= d.id %>" <%= selected %>><%= d.name %></option>
        <% end %>
        </select></div>
  	</td>
    <td>
      <div class="select"><select style="font-size: 80% !important;" name="rh_group" onchange="this.form.submit()">
        <option value="">--</option>
      <% User.select(:rh_group).distinct.each do |g| 
        next if g.rh_group == ''
        selected = ""
        selected = "selected = 'selected'" if g.rh_group == @rh_group %>
          <option value="<%= g.rh_group %>" <%= selected %>><%= g.rh_group %></option>
        <% end %>
        </select></div>
    </td>
  	<td>
      <div class="select"><select style="font-size: 80% !important;" name="user_id" onchange="this.form.submit()">
      	<option value="">--</option>
      	<% if !@department_id.blank? 
      	      users = User.where(status: User::ACTIVE, department_id: @department_id).order(:first_name, :last_name)
           else 
           	  users = User.where(status: User::ACTIVE).order(:last_name, :first_name)
           end
           if !@rh_group.blank?
              users = users.where(rh_group: @rh_group)
           end

           if params[:show_type] == 'E' 
              users = users.where('is_student': false).where("rh_level <> 'CAT'")
            end

            if params[:show_type] == 'C' 
              users = users.where('rh_level': 'CAT')
            end

            if params[:show_type] == 'A' 
              users = users.where('is_student': true)
            end
  		   users.each do |emp| 
  		   	 selected = ""
             selected = "selected = 'selected'" if emp.id.to_i == @user_id.to_i %>
             <option value="<%= emp.id %>" <%= selected %>><%= emp.last_name %> <%= emp.first_name %></option>
          <% end %>
        </select></div>
  	</td>
  	<td><input type="date" style="font-size: 80% !important;" class="input" name="date_start" value="<%= @date_start %>" onchange="this.form.submit()"></td>
  	<td><input type="date" style="font-size: 80% !important;" class="input" name="date_end" value="<%= @date_end %>" onchange="this.form.submit()"></td>
  </tr>
</table>
<% if @schedules.count > 0 %>
<div style="text-align: center; margin: 1em; font-size: 1.5em;">
<a onclick="doxls()">Versión excel</a>
</div>
<table class="table is-fullwidth is-hoverable is-bordered schedule-table small-table">
  <tr>
  	<th></th>
  	<th></th>
  	<th>#</th>
    <th>Nombre</th>
    <th>Tipo</th>
    <th>Nivel</th>
    <th>Departamento</th>
  	<th>Fecha</th>
  	<th>Motivo</th>
  	<th>Autorizó</th>
  	<th class="td-center"><span title="Temperatura">Temp.</span></th>
  	<th class="td-center">Entrada</th>
  	<th class="td-center">Salida</th>
    <th class="td-center">Horas</th>
  	<th class="td-center">Notas Salida</th>
    <th></th>
  </tr>
  <% total = 0 %>
  <% @schedules.each do |s| %>
    <% next if !@show_students && s.user.is_student   %>
    <% total = total + 1 %>
    <tr>
      <td class="td-center">
      	<% if s.passed.nil? %>
  	      <span class="icon has-text-warning"><i class="fas fa-exclamation"></i></span>
        <% elsif s.passed %>
          <span class="icon has-text-success"><i class="fas fa-check"></i></span>
        <% else %>
          <span class="icon has-text-danger"><i class="fas fa-times"></i></span>
        <% end %>
      </td>
      <td class="td-img td-center"><img class="is-rounded" src="<%= s.user.display_url %>"><br>
      <% if s.user.is_student  %>
        <span class="tag is-warning  is-light">Estudiante</span>
        <% else %>
        <span class="tag is-primary  is-light">Empleado</span>
        <% end %></td>
      <td><%= s.user.rh_id %></td>
      <td><%= s.user.fullname %></td>
      <td><%= s.user.rh_group %></td>
      <td><%= s.user.rh_level %></td>
      <td><%= s.user.department.name %></td>
      <td>
        	
      	<% if s.h1 && s.h2 
    	  	hours = "Todo el día"
    	  elsif s.h1 && !s.h2 
    	  	hours = "De 6:00 a 12:00"
    	  else
    	    hours = "De 13:00 a 19:00"
    	  end	
        %>
        <%= s.work_date %> <%= hours %>
      </td>
      <td><%= s.notes %></td>
      <td><%= s.authorized_by.first_name %> <%= s.authorized_by.last_name %><br><span class="tag is-light"><%= s.authorized_by.department.name rescue 'Sin departamento' %></span></td>
      <td class="td-center"><%= s.temperature %></td>
      <% if s.user.location.name != 'Chihuahua'
          plus_in = s.in + 1.hours rescue '--'
          plus_out = s.out + 1.hours rescue '--'
      %>
          <td class="td-center"><%= l plus_in.to_datetime, format: "%H:%M" rescue '--' %></td>
          <td class="td-center"><%= l plus_out.to_datetime, format: "%H:%M" rescue '--' %></td>
      <% else %>
          <td class="td-center"><%= l s.in.to_datetime, format: "%H:%M" rescue '--' %></td>
          <td class="td-center"><%= l s.out.to_datetime, format: "%H:%M" rescue '--' %></td>
      <% end %>
      <td class="td-center"><%= ((s.out - s.in) / 1.hours).round(2) rescue '--' %></td>
      <td><%= s.out_notes %></td>
      <td>
        <% if is_admin? %>
          <a href="<%= edit_schedule_path(s) %>">Editar</a>
        <% end %>
        <% if !s.edit_notes.blank? %>
          <br>
          <strong><%= s.edit_by_user.fullname %>:</strong><br><%= s.edit_notes %><br><%= l s.edit_date.to_datetime, format: "%Y-%m-%d %H:%M" rescue '--'  %>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>
<% else %>
<div class="not-today">
  No hay registros
</div>
<% end %>
</form>
<script>
  function doxls() {
    document.reportform.action = "/reporte/xls";
    document.reportform.submit();
    document.reportform.action = "/reporte";
  }
</script>